src/blog/urls.py
from django.urls import path
from blog.views import(

		create_blog_view,
		detail_blog_view,
		edit_blog_view,
		# comment_view
	)

app_name = 'blog' # use this whenever a main app file like urls.py is made seaprately in some other folder

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
	path('<slug>/edit', edit_blog_view, name="edit"),
	#path('<slug>/comments', comment_view, name="comments")			
]

src/comments/urls.py
from django.urls import path
from comments.views import(

		create_comment_view,
		edit_comment_view,
		# comment_view
	)

app_name = 'comments' # use this whenever a main app file like urls.py is made seaprately in some other folder

urlpatterns = [
	path('create/', create_comment_view, name="create"),
	path('<slug>/edit', edit_comment_view, name="edit"),
	#path('<slug>/comments', comment_view, name="comments")			
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
	home_screen_view,
	)

from account.views import (
        registration_view,
        logout_view,
        login_view,
        account_view,
        must_authenticate_view,
    )


urlpatterns = [
    path('', home_screen_view, name = 'home'),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),
    path('blog/', include('blog.urls' , "blog" )), 
    # to include urls.py form blog folder, and any URL from blog folder will start from blog/
    path('comments/', include('comments.urls' , "comments" )),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),


    #path('account/', include('django.contrib.auth.urls')),
    # Copied links from mitch github. Ex =auth_views.PasswordChangeDoneView ==these are default views created in django.contrib.auth. 
    #link: https://docs.djangoproject.com/en/1.8/_modules/django/contrib/auth/views/
    # password_change_done.html== Thse are the custom templates we will create to modify these default views
    # 'password_change/done/' == These URLs must be present for password reset, (shown in django doc)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'), # use exact same names to avoid errors

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG: #if in dev env, this is telling where the media and static urls are
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/comments/models.py
from django.db import models
from django.db import models
from blog.models import BlogPost
from django.db.models.signals import pre_save,post_delete
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver

# CODE BY ME

def upload_location(instance,filename):
	# purple is the path for blog/ a image filename
	file_path = 'comments/{blog_id}/{comment_text}'.format(
			blog_id=str(instance.blog_id), title=str(instance.comment_text)
		)
	return file_path

class comments(models.Model):
	blog 							= models.ForeignKey(BlogPost, on_delete = models.CASCADE) #Delete blogpost, comment will get deleted.
	comment_text					= models.TextField(max_length=400, null=False, blank=False)
	date_published					= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated					= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author 							= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE) 
	slug 							= models.SlugField(blank=True, unique=True)
	def __str__(self):
		return self.comment_text

def pre_save_comments_reciever(sender, instance,*args,**kwargs):
	if not instance.slug: # if no unique slug is created before saving then create it
		instance.slug = slugify(instance.comment_text[:4])

pre_save.connect(pre_save_comments_reciever, sender=comments) # whenever a saveing attempt is made above function will be called



#END CODE BY ME

src/comments/forms.py
from django import forms
from blog.models import BlogPost
from comments.models import comments
from account.models import Account

class CreateCommentForm(forms.ModelForm):

	class Meta:
		model = comments
		fields = ['comment_text'] #refer to models

class UpdateCommentForm(forms.ModelForm):
	class Meta:
		model = comments
		fields = ['comment_text']

	def save(self, commit=True):
		comment = self.instance #this should be the comment object having dates,authours,etc.
		comment.comment_text = self.cleaned_data['comment_text'] 

		if commit:
			comment.save()

		return comment

src/comments/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect,get_object_or_404
from django.db.models import Q
from django.http import HttpResponse
#FROM BLOGS
from blog.models import BlogPost
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
#FROM COMMENTS
from comments.models import comments
# and pre_save_comments_reciever is also there
from comments.forms import CreateCommentForm, UpdateCommentForm
#FROM ACCOUNTS
from account.models import Account

# Create your views here.

def create_comment_view(request,slug):
	context = {}

	user =  request.user
	if not user.is_authenticated:
		return redirect('must_authenticate') # redirects to must authenticate.html

	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit = False)
		author = Account.objects.filter(email=user.email).first() # filter the user using email
 # author is a required field in forms.py BlogPostForm
		obj.author = author 
		obj.save()
		form = CreateBlogPostForm()
		
	context['form'] = form

	return render(request,"comments/create_comment.html", context)


def edit_comment_view(request, slug):
	context = {}
	user = request.user
	if not user.is_authenticated:
		return redirect('must_authenticate') 

	comment = get_object_or_404(comments, slug = slug)

	if comment.author != user:
		return HttpResponse('You are not the author of that post.')

	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance= comment)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			comment = obj
	form = UpdateCommentForm(
			initial = {
					"comment_text": comment.comment_text,
			}
		)
	context['form'] = form
	return render(request, 'comment/edit_comment.html', context)

def get_comment_queryset(query=None): #Used in homescreenview in views.py - personal
	queryset = []
	queries = query.split(" ") 
	for q in queries:
		posts = comments.objects.filter(
				Q(comment_text__icontains=q)
			).distinct()
# Q lookup imported above, use double underscores
		for post in posts:
			queryset.append(post)

	return list(set(queryset))

src/comments/templates/comments/snippets/comment_pagination.html
 FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if comment_text.has_previous %} 
<!-- blog_posts defined in home_screen view -->
        <li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ comment_text.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in comment_text.paginator.page_range %}
		{% if comment_text.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if comment_text.has_next %}
    	<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ comment_text.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ comment_text.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination

src/comments/templates/comments/snippets/comment_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
		width: 100%
	}
</style>
<!-- blog_post in edit_blog_view and in forms.py-blog-->
{% if comment %}
<div class="container">
	<div class="row">
		<!-- Blog Post -->
		<div class="card m-auto">
			<a href="{% url 'blog:detail' post.slug %}">
				<img class="card-img-top" src="{{blog_post.image.url}}">
			</a>
			<div class="card-body mt-2 mb-2">
				<p class="card-text">{{comment.comment_text|safe|truncatechars:250}}</p>
				<p>
				{% if comment.author == request.user %}
					<a href="{% url 'comments:edit' comment.slug %}" class="btn btn-primary">Update</a>
				{% endif %}
				</p>
			</div>
			<div class="card-footer text-muted">
			  Updated on {{comment.date_updated}} by {{comment.author}}
			</div>
		</div>
	</div>
</div>
{% endif %}