src/blog/urls.py
from django.urls import path
from blog.views import(

		create_blog_view,
		detail_blog_view,
		edit_blog_view,
		# comment_view
	)

app_name = 'blog' # use this whenever a main app file like urls.py is made seaprately in some other folder

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
	path('<slug>/edit', edit_blog_view, name="edit"),
	#path('<slug>/comments', comment_view, name="comments")			
]

src/comments/urls.py
from django.urls import path
from comments.views import(

		create_comment_view,
		edit_comment_view,
		# comment_view
	)

app_name = 'comments' # use this whenever a main app file like urls.py is made seaprately in some other folder

urlpatterns = [
	path('create/', create_comment_view, name="create"),
	path('<slug>/edit', edit_comment_view, name="edit"),
	#path('<slug>/comments', comment_view, name="comments")			
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (
	home_screen_view,
	)

from account.views import (
        registration_view,
        logout_view,
        login_view,
        account_view,
        must_authenticate_view,
    )


urlpatterns = [
    path('', home_screen_view, name = 'home'),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),
    path('blog/', include('blog.urls' , "blog" )), 
    # to include urls.py form blog folder, and any URL from blog folder will start from blog/
    path('comments/', include('comments.urls' , "comments" )),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),


    #path('account/', include('django.contrib.auth.urls')),
    # Copied links from mitch github. Ex =auth_views.PasswordChangeDoneView ==these are default views created in django.contrib.auth. 
    #link: https://docs.djangoproject.com/en/1.8/_modules/django/contrib/auth/views/
    # password_change_done.html== Thse are the custom templates we will create to modify these default views
    # 'password_change/done/' == These URLs must be present for password reset, (shown in django doc)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'), # use exact same names to avoid errors

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG: #if in dev env, this is telling where the media and static urls are
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models

from django.db.models.signals import pre_save,post_delete
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver
# Create your models here.
 # for defining image upload location

def upload_location(instance,filename):
	# purple is the path for blog/ a image filename
	file_path = 'blog/{author_id}/{title}-{filename}'.format(
			author_id=str(instance.author_id), title=str(instance.title),filename=filename
		)
	return file_path

class BlogPost(models.Model):
	title					= models.CharField(max_length=50, null=False, blank=False) # a blog can't be null or blank
	body					= models.TextField(max_length=5000, null=False, blank=False) #blog body
	image					= models.ImageField(upload_to=upload_location, null= False, blank=False)
	date_published			= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated			= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author 					= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE) 
	# foreign key is same as SQL to join Blogpost with account, but instead of importing it directly here we are saying
	# use the one specified in settings. On deletion, blog only should be deleted not the user.
	slug 					= models.SlugField(blank=True, unique=True)
	#slug means the /(some extra) portion of URL. That should be unique for every blog post.

	def __str__(self):
		return self.title

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
	instance.image.delete(False)
#This will clean image from the development env after blog is deleted to save data

def pre_save_blog_post_reciever(sender, instance,*args,**kwargs):
	if not instance.slug: # if no unique slug is created before saving then create it
		instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_reciever, sender=BlogPost) # whenever a saveing attempt is made above function will be called

src/comments/models.py
from django.db import models
from django.db import models
from blog.models import BlogPost
from django.db.models.signals import pre_save,post_delete
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver

# CODE BY ME

def upload_location(instance,filename):
	# purple is the path for blog/ a image filename
	file_path = 'comments/{blog_id}/{comment_text}'.format(
			blog_id=str(instance.blog_id), title=str(instance.comment_text)
		)
	return file_path

class comments(models.Model):
	blog 							= models.ForeignKey(BlogPost, on_delete = models.CASCADE) #Delete blogpost, comment will get deleted.
	comment_text					= models.TextField(max_length=400, null=False, blank=False)
	date_published					= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated					= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author 							= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE) 
	slug 							= models.SlugField(blank=True, unique=True)
	def __str__(self):
		return self.comment_text

def pre_save_comments_reciever(sender, instance,*args,**kwargs):
	if not instance.slug: # if no unique slug is created before saving then create it
		instance.slug = slugify(instance.comment_text[:4])

pre_save.connect(pre_save_comments_reciever, sender=comments) # whenever a saveing attempt is made above function will be called



#END CODE BY ME

src/comments/forms.py
from django import forms
from blog.models import BlogPost
from comments.models import comments
from account.models import Account

class CreateCommentForm(forms.ModelForm):

	class Meta:
		model = comments
		fields = ['comment_text'] #refer to models

class UpdateCommentForm(forms.ModelForm):
	class Meta:
		model = comments
		fields = ['comment_text']

	def save(self, commit=True):
		comment = self.instance #this should be the comment object having dates,authours,etc.
		comment.comment_text = self.cleaned_data['comment_text'] 

		if commit:
			comment.save()

		return comment

src/comments/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect,get_object_or_404
from django.db.models import Q
from django.http import HttpResponse
#FROM BLOGS
from blog.models import BlogPost
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
#FROM COMMENTS
from comments.models import comments
# and pre_save_comments_reciever is also there
from comments.forms import CreateCommentForm, UpdateCommentForm
#FROM ACCOUNTS
from account.models import Account

# Create your views here.

def create_comment_view(request,slug):
	context = {}

	user =  request.user
	if not user.is_authenticated:
		return redirect('must_authenticate') # redirects to must authenticate.html

	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit = False)
		author = Account.objects.filter(email=user.email).first() # filter the user using email
 # author is a required field in forms.py BlogPostForm
		obj.author = author 
		obj.save()
		form = CreateBlogPostForm()
		
	context['form'] = form

	return render(request,"comments/create_comment.html", context)


def edit_comment_view(request, slug):
	context = {}
	user = request.user
	if not user.is_authenticated:
		return redirect('must_authenticate') 

	comment = get_object_or_404(comments, slug = slug)

	if comment.author != user:
		return HttpResponse('You are not the author of that post.')

	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance= comment)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			comment = obj
	form = UpdateCommentForm(
			initial = {
					"comment_text": comment.comment_text,
			}
		)
	context['form'] = form
	return render(request, 'comment/edit_comment.html', context)

def get_comment_queryset(query=None): #Used in homescreenview in views.py - personal
	queryset = []
	queries = query.split(" ") 
	for q in queries:
		posts = comments.objects.filter(
				Q(comment_text__icontains=q)
			).distinct()
# Q lookup imported above, use double underscores
		for post in posts:
			queryset.append(post)

	return list(set(queryset))

src/comments/templates/create_comment.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- comment_text -->
				<div class="form-group">
					<label for="id_title">comment_text</label>
					<input class="form-control" type="text" name="comment_text" id="id_comment_text" placeholder="comment text" required autofocus>
				</div>
				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Comment</button>
			</form>	
		</div>
	</div>
</div>

{% endblock content %}

src/comments/templates/detail_comment.html
	{% extends "base.html" %}

	{% block content %}
	<style type="text/css">
		.card {
			max-width: 700px;
		}

		.container{
			padding: 20px;
		}
	</style>

<div class = 'container'>
	<div class="row">
		<!-- Blog Post -->
		<div class="card m-auto">
			<div class="card-body my-2">
				<h2 class="card-title">{{comment.comment_text}}</h2>

				<p>
				{% if comment.author == request.user %}
					<a href= "{% url 'comment:edit' comment.slug %}" class="btn btn-primary">Update</a>
					<!-- Adding a button for editing blog post if user and post aurthor are same -->
				{% endif %}
				</p>
			</div>
			<div class="card-footer text-muted">
				Updated on {{comment.date_updated}} bu {{comment.author}}	
			</div>
		</div>
		<!-- End Blog Post -->

	</div>		
</div>

src/comments/templates/edit_comment.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- comment_text -->
				<div class="form-group">
					<label for="id_title">comment_text</label>
					<input class="form-control" type="text" name="comment_text" id="id_comment_text" placeholder="comment text" value="{{form.initial.comment_text}}" required autofocus>
				</div>

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

{% endblock content %}